name: home_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_animate: ^4.5.0
  onboarding_animation: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/.env
   

 
  fonts:
    - family: PS
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
          
    - family: LS
      fonts:
        - asset: assets/fonts/LS/LeagueSpartan-Bold.ttf
          weight: 700
        - asset: assets/fonts/LS/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LS/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LS/LeagueSpartan-Regular.ttf
          weight: 400
        - asset: assets/fonts/LS/LeagueSpartan-Light.ttf
          weight: 300
        - asset: assets/fonts/LS/LeagueSpartan-Thin.ttf
          weight: 100
